name: Master
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 06:00 UTC
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: 23f2003577@ds.study.iitm.ac.in
        run: |
          "Running!"
